' Таблица 2 – Сравнение классов программных решений для склада
@startsalt
{#
|Тип |Плюсы |Минусы |
|ERP |Интеграция с финансами, единое пространство |Стоимость, сложность внедрения |
|WMS |Складская детализация, адресное хранение |Нужна интеграция с ERP |
|Специализированная |Адаптация под процесс |Поддержка своими силами |
}
@endsalt
